/**
 * Gerenciamento de Veículos
 * Exemplo de API REST criada com o ASP.NET Core
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MotoristaVeiculo } from './motoristaVeiculo';


export interface Motorista { 
    id?: string;
    email?: string | null;
    primeiroNome?: string | null;
    sobreNome?: string | null;
    readonly nomeCompleto?: string | null;
    motoristaVeiculos?: Array<MotoristaVeiculo> | null;
}

