/**
 * Gerenciamento de Veículos
 * Exemplo de API REST criada com o ASP.NET Core
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MotoristaVeiculo } from './motoristaVeiculo';


export interface Veiculo { 
    id?: string;
    marca?: string | null;
    modelo?: string | null;
    placa?: string | null;
    localidade?: string | null;
    motoristaVeiculos?: Array<MotoristaVeiculo> | null;
}

